"""Exploration of the chunks generated by chunk_corpus.py.

Reads the local manifests and downloads the chunks from Cleyrop on demand.

Usage:
    uv run scripts/inspect/explore_chunks.py [OPTIONS]

    --name <fragment>    find by filename fragment
    --source-id <id>     chunks of a specific document (Cleyrop file_id)
    --random             pick a random document
    --middle             show chunks taken from the middle of the document
    --limit N            show at most N chunks (default: 10)
    --preview N          characters shown per chunk (default: 600)
    --stats-only         show statistics only
    --manifests-dir      output/manifests (default)
    --config             configs/chunker.yaml (default)
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
import tomllib
from pathlib import Path

from dotenv import load_dotenv

from cleyrop import CleyropClient, ClientConfig

load_dotenv(override=True)

_config_path = Path(__file__).parent.parent.parent / "config.toml"
with open(_config_path, "rb") as f:
    _config = tomllib.load(f)


# ─────────────────────────── cleyrop helpers ─────────────────────────────────


def make_config() -> ClientConfig:
    domain = os.environ.get("CLEYROP_DOMAIN") or _config["cleyrop"].get("domain")
    if domain:
        os.environ.setdefault("CLEYROP_DOMAIN", domain)
        return ClientConfig.from_env()
    return ClientConfig.internal(
        client_id=os.environ.get("CLEYROP_CLIENT_ID", "cleyrop-cli"),
        client_secret=os.environ.get("CLEYROP_CLIENT_SECRET"),
        token=os.environ.get("CLEYROP_TOKEN"),
    )


def resolve_project_id(cfg: ClientConfig) -> str:
    client = CleyropClient(cfg)
    if cfg.client_secret:
        client.login_client_credentials()
    with client:
        if project_id := os.environ.get("PROJECT_ID"):
            return project_id
        if project_id := _config["project"].get("id"):
            return project_id
        project_slug = os.environ["PROJECT_SLUG"]
        return str(client.get_project_by_slug(project_slug).id)


def find_chunks_folder_ids(client: CleyropClient, project_id: str, folder_name: str) -> list[str]:
    """Return the IDs of every folder whose name starts with folder_name."""
    contents = client.get_project_contents(project_id)
    return [
        str(f.id) for f in contents.folders
        if f.name == folder_name or f.name.startswith(folder_name + "_")
    ]


def download_chunks_jsonl(client: CleyropClient, folder_ids: list[str], file_id: str) -> list[dict]:
    """Download and parse the chunk JSONL for a given file_id (searches every folder)."""
    target_name = f"{file_id}.jsonl"
    for folder_id in folder_ids:
        contents = client.get_folder_contents(folder_id)
        for item in contents.files:
            if item.name == target_name:
                raw = client.download_file_bytes(item.id)
                lines = raw.decode("utf-8").strip().splitlines()
                return [json.loads(line) for line in lines if line.strip()]
    return []


# ─────────────────────────── manifest helpers ────────────────────────────────


def load_all_manifests(manifests_dir: Path) -> list[dict]:
    if not manifests_dir.exists():
        return []
    result = []
    for p in manifests_dir.glob("*.json"):
        with open(p, "r", encoding="utf-8") as f:
            result.append(json.load(f))
    return result


def find_manifest_by_name(manifests: list[dict], fragment: str) -> list[dict]:
    frag = fragment.lower()
    return [m for m in manifests if frag in m.get("name", "").lower()]


# ─────────────────────────── display ─────────────────────────────────────────

SEP = "─" * 60


def print_chunk(chunk: dict, index: int, preview: int) -> None:
    text = chunk["text"]
    print(SEP)
    print(f"Chunk #{index:03d}  │  {len(text)} chars  │  {chunk['name']}")
    headings = chunk.get("docling_meta", {}).get("headings", [])
    if headings:
        print(f"  Section: {' > '.join(headings)}")
    print()
    if preview == 0 or len(text) <= preview:
        print(text)
    else:
        print(text[:preview])
        print(f"  … [{len(text) - preview} chars remaining]")
    print()


def print_stats(chunks: list[dict], name: str) -> None:
    if not chunks:
        print("No chunks found.")
        return
    lengths = [len(c["text"]) for c in chunks]
    with_headings = sum(1 for c in chunks if c.get("docling_meta", {}).get("headings"))
    docs = {c["file_id"] for c in chunks}
    print(f"\nStatistics — {name}")
    print(SEP)
    print(f"  Documents      : {len(docs)}")
    print(f"  Total chunks   : {len(chunks)}")
    print(f"  Avg length     : {sum(lengths) // len(lengths)} chars")
    print(f"  Min / Max      : {min(lengths)} / {max(lengths)} chars")
    print(f"  With headings  : {with_headings} ({100*with_headings//len(chunks)}%)")
    print()


# ─────────────────────────── main ────────────────────────────────────────────


def pick_chunks(chunks: list[dict], limit: int, middle: bool) -> list[dict]:
    if not middle:
        return chunks[:limit]
    n = len(chunks)
    start = max(0, n // 2 - limit // 2)
    return chunks[start: start + limit]


def main() -> None:
    parser = argparse.ArgumentParser(description="Exploration of the IRSN chunks")
    parser.add_argument("--name", default=None, help="Filename fragment")
    parser.add_argument("--source-id", default=None, help="Exact Cleyrop file_id")
    parser.add_argument("--random", action="store_true", help="Random document")
    parser.add_argument("--middle", action="store_true", help="Chunks from the middle of the doc")
    parser.add_argument("--limit", type=int, default=10)
    parser.add_argument("--preview", type=int, default=None, help="Chars per chunk (default: 0 if --middle, 600 otherwise)")
    parser.add_argument("--stats-only", action="store_true")
    parser.add_argument("--manifests-dir", default="output/manifests")
    parser.add_argument("--config", default="configs/chunker.yaml")
    args = parser.parse_args()

    root = Path(__file__).parent.parent.parent
    manifests_dir = root / args.manifests_dir

    import yaml
    config_path = root / args.config
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    chunks_folder_name = cfg["storage"]["chunks_folder"]

    all_manifests = load_all_manifests(manifests_dir)
    done_manifests = [m for m in all_manifests if m.get("status") == "done"]

    if not args.name and not args.source_id and not args.random:
        print_stats([], "corpus")
        print(f"Documents processed: {len(done_manifests)} / {len(all_manifests)}")
        print("Use --name, --source-id or --random to explore the chunks.")
        return

    if args.random:
        if not done_manifests:
            print("No processed documents.")
            sys.exit(1)
        targets = [random.choice(done_manifests)]
        print(f"Randomly selected document: {targets[0]['name']}")
    elif args.source_id:
        targets = [m for m in done_manifests if m["file_id"] == args.source_id]
    else:
        targets = find_manifest_by_name(done_manifests, args.name)

    if not targets:
        print(f"No chunked document found for: {args.name or args.source_id}")
        print(f"({len(done_manifests)} documents processed in total)")
        sys.exit(1)

    cleyrop_cfg = make_config()
    project_id = resolve_project_id(cleyrop_cfg)

    all_chunks: list[dict] = []

    with CleyropClient(cleyrop_cfg) as client:
        if cleyrop_cfg.client_secret:
            client.login_client_credentials()

        folder_ids = find_chunks_folder_ids(client, project_id, chunks_folder_name)
        if not folder_ids:
            print(f"Folder '{chunks_folder_name}' not found in Cleyrop.")
            sys.exit(1)

        for m in targets:
            print(f"Loading: {m['name']} ({m['num_chunks']} chunks)")
            chunks = download_chunks_jsonl(client, folder_ids, m["file_id"])
            all_chunks.extend(chunks)

    print_stats(all_chunks, args.name or args.source_id or targets[0]["name"])

    if not args.stats_only:
        preview = args.preview if args.preview is not None else (0 if args.middle else 600)
        display = pick_chunks(all_chunks, args.limit, args.middle)
        offset = all_chunks.index(display[0]) if display else 0
        for i, chunk in enumerate(display):
            print_chunk(chunk, offset + i, preview)
        remaining = len(all_chunks) - offset - len(display)
        if remaining > 0:
            print(f"… {remaining} more chunks (increase --limit)")


if __name__ == "__main__":
    main()
